### ISSUE TITLE
Causes issue as of June 1st.

### ISSUE THREAD

**Issue by refriedfood** [Tibladar/StopDiscordTracking#1]
Whatever discord updated now causes this plugin to fail at reading/fetching channel, pm, history, or text messages in discord while enabled. This forces you to disable the plugin and reload (ctrl+r) in order to view channels and their text properly.

![img](https://images2.imgbox.com/bf/a6/Cc3yaIfE_o.png)

**Comment by Tibladar** [comment]
Thanks for reporting, this should be fixed with 2c60ce82228e0305d2a9cead0017dd4f278f566c

**Comment by Tibladar** [comment]
However, please note that it isn't updated automatically.
